### PR TITLE
MHState

### PR DESCRIPTION
**Pull request by JaimeRZP**
Creates 
```Julia
struct MHState{TTrans<:Transition}
    "Random number of the state"
    rng::Random.AbstractRNG
    "Index of current iteration."
    i::Int
    "Current [`Transition`](@ref)."
    transition::TTrans
end
```
which allows the sampling to restart by savign the iteration and rng of the sampler.

### CODE REVIEW

**Comment by devmotion** [comment]
I'm pretty sure in its current form the PR won't solve the problem - it seems the RNG object is saved in the transition but all subsequent calls of `rand` with this RNG object (eg in subsequent sampling steps) will mutate the state of the RNG and hence mutate the RNG saved in the transition.

**Comment by devmotion** [comment]
I'm pretty sure there was a discussion about saving RNGs in some repo at some point, and IIRC I was arguing that it's a more general problem that should be addressed in AbstractMCMC. For instance, by outputting/saving the RNG after the final step and inxluding it in the chain (deep copied?) if possible. Deep copying the RNG in every sampling step seems a bit wasteful to me and would slow down sampling, and only saving the initial RNG and the step number would mean you always have to rerun the whole sampling if you want to continue sampling - which means it would be as slow as running a single chain with all samples.

**Comment by cpfiffer** [comment]
I agree that this won't solve the problem -- this should be done upstream in AbstractMCMC. It'd be nice to store the seeds in each transition (which should be cheap) rather than deep copying the rng.

**Comment by JaimeRZP** [comment]
Agreed! Closing the PR. 
Thanks for the discussion!

**Pull request closed without merging**
